import type { AchievementDefinition } from '@/types/content';

export const BASE_ACHIEVEMENTS: readonly AchievementDefinition[] = [
  {
    id: 'ach_first_scan',
    key: 'first_scan',
    name: 'First Discovery',
    description: 'Scan your first product',
    emoji: '🎉',
    unlockCondition: 'scan_count',
    threshold: 1,
    rewardXp: 50,
  },
  {
    id: 'ach_explorer',
    key: 'explorer',
    name: 'Curious Explorer',
    description: 'Scan 10 products',
    emoji: '🔍',
    unlockCondition: 'scan_count',
    threshold: 10,
    rewardXp: 100,
  },
  {
    id: 'ach_collector',
    key: 'collector',
    name: 'Collection Keeper',
    description: 'Scan 25 products',
    emoji: '📦',
    unlockCondition: 'scan_count',
    threshold: 25,
    rewardXp: 200,
  },
  {
    id: 'ach_veteran',
    key: 'veteran',
    name: 'Seasoned Companion',
    description: 'Scan 50 products',
    emoji: '⭐',
    unlockCondition: 'scan_count',
    threshold: 50,
    rewardXp: 300,
  },
  {
    id: 'ach_master',
    key: 'master',
    name: 'Discovery Master',
    description: 'Scan 100 products',
    emoji: '🏆',
    unlockCondition: 'scan_count',
    threshold: 100,
    rewardXp: 500,
  },
  {
    id: 'ach_first_register',
    key: 'first_register',
    name: 'Contributor',
    description: 'Register your first product',
    emoji: '✨',
    unlockCondition: 'register_count',
    threshold: 1,
    rewardXp: 75,
  },
  {
    id: 'ach_curator',
    key: 'curator',
    name: 'Product Curator',
    description: 'Register 5 products',
    emoji: '📝',
    unlockCondition: 'register_count',
    threshold: 5,
    rewardXp: 150,
  },
  {
    id: 'ach_level_5',
    key: 'level_5',
    name: 'Growing Together',
    description: 'Reach level 5',
    emoji: '🌱',
    unlockCondition: 'level',
    threshold: 5,
    rewardXp: 100,
  },
  {
    id: 'ach_level_10',
    key: 'level_10',
    name: 'Steady Bond',
    description: 'Reach level 10',
    emoji: '🌿',
    unlockCondition: 'level',
    threshold: 10,
    rewardXp: 200,
  },
  {
    id: 'ach_level_25',
    key: 'level_25',
    name: 'Deep Connection',
    description: 'Reach level 25',
    emoji: '🌳',
    unlockCondition: 'level',
    threshold: 25,
    rewardXp: 500,
  },
  {
    id: 'ach_streak_3',
    key: 'streak_3',
    name: 'Daily Routine',
    description: 'Visit 3 days in a row',
    emoji: '🔥',
    unlockCondition: 'streak',
    threshold: 3,
    rewardXp: 75,
  },
  {
    id: 'ach_streak_7',
    key: 'streak_7',
    name: 'Weekly Companion',
    description: 'Visit 7 days in a row',
    emoji: '💫',
    unlockCondition: 'streak',
    threshold: 7,
    rewardXp: 150,
  },
  {
    id: 'ach_streak_30',
    key: 'streak_30',
    name: 'Dedicated Caretaker',
    description: 'Visit 30 days in a row',
    emoji: '💝',
    unlockCondition: 'streak',
    threshold: 30,
    rewardXp: 500,
  },
] as const;
