import type { MissionDefinition } from '@/types/content';

export const BASE_DAILY_MISSIONS: readonly MissionDefinition[] = [
  {
    id: 'daily_scan_3',
    type: 'daily',
    name: 'Morning Discoveries',
    description: 'Scan 3 products today',
    objective: 'scan_any',
    target: 3,
    rewardXp: 50,
  },
  {
    id: 'daily_scan_5',
    type: 'daily',
    name: 'Daily Explorer',
    description: 'Scan 5 products today',
    objective: 'scan_any',
    target: 5,
    rewardXp: 75,
  },
  {
    id: 'daily_register_1',
    type: 'daily',
    name: 'Share Something New',
    description: 'Register a product today',
    objective: 'register_any',
    target: 1,
    rewardXp: 100,
  },
  {
    id: 'daily_snack_scan',
    type: 'daily',
    name: 'Snack Time',
    description: 'Scan a snack today',
    objective: 'scan_category',
    target: 1,
    rewardXp: 50,
    categoryFilter: ['snack'],
  },
  {
    id: 'daily_beverage_scan',
    type: 'daily',
    name: 'Hydration Check',
    description: 'Scan a beverage today',
    objective: 'scan_category',
    target: 1,
    rewardXp: 50,
    categoryFilter: ['beverage'],
  },
  {
    id: 'daily_variety_3',
    type: 'daily',
    name: 'Variety Seeker',
    description: 'Scan 3 different product types',
    objective: 'scan_any',
    target: 3,
    rewardXp: 75,
  },
] as const;

export const BASE_WEEKLY_MISSIONS: readonly MissionDefinition[] = [
  {
    id: 'weekly_scan_15',
    type: 'weekly',
    name: 'Weekly Wanderer',
    description: 'Scan 15 products this week',
    objective: 'scan_any',
    target: 15,
    rewardXp: 200,
  },
  {
    id: 'weekly_scan_30',
    type: 'weekly',
    name: 'Dedicated Explorer',
    description: 'Scan 30 products this week',
    objective: 'scan_any',
    target: 30,
    rewardXp: 400,
  },
  {
    id: 'weekly_register_3',
    type: 'weekly',
    name: 'Weekly Contributor',
    description: 'Register 3 products this week',
    objective: 'register_any',
    target: 3,
    rewardXp: 300,
  },
  {
    id: 'weekly_daily_visit',
    type: 'weekly',
    name: 'Daily Companion',
    description: 'Visit every day this week',
    objective: 'time_based',
    target: 7,
    rewardXp: 250,
  },
] as const;
